### ISSUE TITLE
cannot install the plugins in redmine 3.3.X

### ISSUE THREAD

**Issue by archonwang** [nmikhno/redmine_estimates#2]
I installed it on Redmine 3.3.X and found it conflict with other plugins
the error log is 

>   Rendered plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base (9817.1ms)
> Completed 500 Internal Server Error in 10161ms (ActiveRecord: 53.9ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.6ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.0ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (12.9ms)
> 
> ActionView::Template::Error (undefined method `render_issue_self_and_descendants_tree' for #<#<Class:0x007f2dd8887310>:0x007f2df42b9458>):
>     3: <div id="issue_tree">
>     4:   <% @issue.ancestors.visible.all.each do |i| %>
>     5:     <% if i.root? %>
>     6:       <%= render_issue_self_and_descendants_tree(i, @issue) %>
>     7:     <% end %>
>     8:   <% end %>
>     9: </div>
>   plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:6:in`block in _plugins_redmine_show_parent_at_subtask_app_views_issues__parent_status_html_erb___259836701
> 3752318347_69917457555960'  plugins/redmine_show_parent_at_subtask/app/views/issues/_parent_status.html.erb:4:in `_plugins_redmine_show_parent_at_subtask_app_views_issues__parent_status_html_erb___259836701375231834
> 7_69917457555960'  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in`render_with_workflow_enhancements'
>   lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
>   lib/redmine/hook/view_listener.rb:57:in`map'
>   lib/redmine/hook/view_listener.rb:57:in `block in render_on'
>   lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
>   lib/redmine/hook.rb:61:in `each'
>   lib/redmine/hook.rb:61:in`block in call_hook'
>   lib/redmine/hook.rb:58:in `tap'
>   lib/redmine/hook.rb:58:in`call_hook'
>   lib/redmine/hook.rb:96:in `call_hook'
>   plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb:142:in`_plugins_redmine_workflow_hidden_fields_app_views_issues_show_html_erb__2133121074716811228_69917463563800'
>   app/controllers/issues_controller.rb:117:in `block (2 levels) in show'
>   app/controllers/issues_controller.rb:114:in`show'
>   plugins/redmine_estimates/lib/issues_controller_patch.rb:30:in `show_with_patch'
>   lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by archonwang** [comment]
@nmikhno 
when I installed the plugin it occured an error

> # bundle exec rake redmine:plugins:migrate NAME=redmine_estimates RAILS_ENV=production

```
Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/scoping/default.rb:87:in `default_scope'
/opt/redmine-3.3/plugins/redmine_estimates/app/models/estimate_entry.rb:16:in `<class:EstimateEntry>'
/opt/redmine-3.3/plugins/redmine_estimates/app/models/estimate_entry.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/redmine-3.3/plugins/redmine_estimates/lib/issue_query_patch.rb:13:in `block in included'
/opt/redmine-3.3/plugins/redmine_estimates/lib/issue_query_patch.rb:7:in `class_eval'
/opt/redmine-3.3/plugins/redmine_estimates/lib/issue_query_patch.rb:7:in `included'
/opt/redmine-3.3/plugins/redmine_estimates/init.rb:15:in `include'
/opt/redmine-3.3/plugins/redmine_estimates/init.rb:15:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.3/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by mr-bantsevich** [comment]
And I have similar problem.
  Redmine version                3.2.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.5.2

Log:
redmine@websecret:~/redmine/plugins$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /home/redmine/redmine)
DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.

Compiling coffeescript files:
---
[COFFEE]> FROM: /home/redmine/redmine/plugins/redmine_time_tracker/app/assets/javascripts/time_tracker2.js.coffee
[COFFEE]> TO: /home/redmine/redmine/public/plugin_assets/redmine_time_tracker/javascripts/time_tracker2.js
[COFFEE]> FROM: /home/redmine/redmine/plugins/redmine_time_tracker/app/assets/javascripts/field_updater.js.coffee
[COFFEE]> TO: /home/redmine/redmine/public/plugin_assets/redmine_time_tracker/javascripts/field_updater.js
[COFFEE]> FROM: /home/redmine/redmine/plugins/redmine_time_tracker/app/assets/javascripts/validators.js.coffee
[COFFEE]> TO: /home/redmine/redmine/public/plugin_assets/redmine_time_tracker/javascripts/validators.js
Compiling sass files:
---
rake aborted!
ArgumentError: Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.)
/var/lib/gems/1.9.1/gems/activerecord-4.2.5.2/lib/active_record/scoping/default.rb:87:in `default_scope'
/home/redmine/redmine/plugins/redmine_estimates/app/models/estimate_entry.rb:16:in `<class:EstimateEntry>'
/home/redmine/redmine/plugins/redmine_estimates/app/models/estimate_entry.rb:1:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:184:in `const_missing'
/home/redmine/redmine/plugins/redmine_estimates/lib/issue_query_patch.rb:13:in `block in included'
/home/redmine/redmine/plugins/redmine_estimates/lib/issue_query_patch.rb:7:in `class_eval'
/home/redmine/redmine/plugins/redmine_estimates/lib/issue_query_patch.rb:7:in `included'
/home/redmine/redmine/plugins/redmine_estimates/init.rb:15:in `include'
/home/redmine/redmine/plugins/redmine_estimates/init.rb:15:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/1.9.1/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `each'
/home/redmine/redmine/lib/tasks/redmine.rake:186:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `each'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/engine.rb:453:in `load_tasks'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/1.9.1/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/home/redmine/redmine/Rakefile:7:in `<top (required)>'
